export const SortedBy = [
  {
    title: "All",
  },
  {
    title: "Service name",
  },
  {
    title: "Service ID",
  },
  {
    title: "External ID",
  },
];

export const ServiceColumns = {
  checked: false,
  id: "ID",
  service: "Service",
  type: "Type",
  provider: "Provider",
  rate: "Rate",
  min: "Min",
  max: "Max",
  status: "Status",
};

export const ServiceInfo = [
  {
    title: "Facebook",
    services: [
      {
        checked: false,
        id: "1",
        service: "Facebook likes",
        type: "Default",
        provider: "naizop.com",
        rate: "0.019",
        min: 10,
        max: 2147483647,
        status: false,
      },
      {
        checked: false,
        id: "2",
        service: "Facebook views",
        type: "Default",
        provider: "naizop.com",
        rate: "0.012",
        min: 10,
        max: 100,
        status: false,
      },
      {
        checked: false,
        id: "3",
        service: "Facebook followers",
        type: "Default",
        provider: "naizop.com",
        rate: "0.015",
        min: 10,
        max: 100,
        status: false,
      },
    ],
  },
  {
    title: "Twitter",
    services: [
      {
        checked: false,
        id: "4",
        service: "Twitter likes",
        type: "Default",
        provider: "naizop.com",
        rate: "0.019",
        min: 10,
        max: 2147483647,
        status: false,
      },
      {
        checked: false,
        id: "5",
        service: "Twitter views",
        type: "Default",
        provider: "naizop.com",
        rate: "0.012",
        min: 10,
        max: 100,
        status: false,
      },
      {
        checked: false,
        id: "6",
        service: "Twitter followers",
        type: "Default",
        provider: "naizop.com",
        rate: "0.015",
        min: 10,
        max: 100,
        status: false,
      },
    ],
  },
  {
    title: "Facebook",
    services: [
      {
        checked: false,
        id: "7",
        service: "Facebook likes",
        type: "Default",
        provider: "naizop.com",
        rate: "0.019",
        min: 10,
        max: 2147483647,
        status: false,
      },
      {
        checked: false,
        id: "8",
        service: "Facebook views",
        type: "Default",
        provider: "naizop.com",
        rate: "0.012",
        min: 10,
        max: 100,
        status: false,
      },
      {
        checked: false,
        id: "9",
        service: "Facebook followers",
        type: "Default",
        provider: "naizop.com",
        rate: "0.015",
        min: 10,
        max: 100,
        status: false,
      },
    ],
  },
  {
    title: "Twitter",
    services: [
      {
        checked: false,
        id: "10",
        service: "Twitter likes",
        type: "Default",
        provider: "naizop.com",
        rate: "0.019",
        min: 10,
        max: 2147483647,
        status: false,
      },
      {
        checked: false,
        id: "11",
        service: "Twitter views",
        type: "Default",
        provider: "naizop.com",
        rate: "0.012",
        min: 10,
        max: 100,
        status: false,
      },
      {
        checked: false,
        id: "12",
        service: "Twitter followers",
        type: "Default",
        provider: "naizop.com",
        rate: "0.015",
        min: 10,
        max: 100,
        status: false,
      },
    ],
  },
  {
    title: "Facebook",
    services: [
      {
        checked: false,
        id: "13",
        service: "Facebook likes",
        type: "Default",
        provider: "naizop.com",
        rate: "0.019",
        min: 10,
        max: 2147483647,
        status: false,
      },
      {
        checked: false,
        id: "14",
        service: "Facebook views",
        type: "Default",
        provider: "naizop.com",
        rate: "0.012",
        min: 10,
        max: 100,
        status: false,
      },
      {
        checked: false,
        id: "15",
        service: "Facebook followers",
        type: "Default",
        provider: "naizop.com",
        rate: "0.015",
        min: 10,
        max: 100,
        status: false,
      },
    ],
  },
  {
    title: "Twitter",
    services: [
      {
        checked: false,
        id: "16",
        service: "Twitter likes",
        type: "Default",
        provider: "naizop.com",
        rate: "0.019",
        min: 10,
        max: 2147483647,
        status: false,
      },
      {
        checked: false,
        id: "17",
        service: "Twitter views",
        type: "Default",
        provider: "naizop.com",
        rate: "0.012",
        min: 10,
        max: 100,
        status: false,
      },
      {
        checked: false,
        id: "18",
        service: "Twitter followers",
        type: "Default",
        provider: "naizop.com",
        rate: "0.015",
        min: 10,
        max: 100,
        status: false,
      },
    ],
  },
  {
    title: "",
  },
];
