export const TextVariants = {
  h1: "h1",
  h2: "h2",
  h3: "h3",
  h4: "h4",
  h5: "h5",
  subtitle_medium: "subtitle_medium",
  subtitle_small: "subtitle_small",
  h1_medium: "h1_medium",
  h2_medium: "h2_medium",
  h3_regular: "h3_regular",
  h4_regular: "h4_regular",
  h5_regular: "h5_regular",
  title: "title",
};

export const IconsVariants = {
  // Bulk
  TrackOrder: "/icons/Bulk/Track.svg",
  VipReward: "/icons/Bulk/Vip reward.svg",
  Add_funds: "/icons/Bulk/Add funds.svg",
  Affiliates: "/icons/Bulk/Affiliates.svg",
  All_services: "/icons/Bulk/All services.svg",
  Api: "/icons/Bulk/Api.svg",
  Blog: "/icons/Bulk/Blog.svg",
  Complited_Orders: "/icons/Bulk/Complited Orders.svg",
  FAQ: "/icons/Bulk/FAQ.svg",
  Favorites: "/icons/Bulk/Favorites.svg",
  Info_Circle: "/icons/Bulk/Info Circle.svg",
  Logout: "/icons/Bulk/Logout.svg",
  Mass_order: "/icons/Bulk/Mass order.svg",
  New_order: "/icons/Bulk/New order.svg",
  Notification_new: "/icons/Bulk/Notification new.svg",
  Notification: "/icons/Bulk/Notification.svg",
  Popular: "/icons/Bulk/Popular.svg",
  Subscriptions_new: "/icons/Bulk/Subscriptions new.svg",
  Subscriptions: "/icons/Bulk/Subscriptions.svg",
  Support_new: "/icons/Bulk/Support new.svg",
  Support: "/icons/Bulk/Support.svg",
  Terms: "/icons/Bulk/Terms.svg",
  Tools: "/icons/Bulk/Tools.svg",
  Updates: "/icons/Bulk/Updates.svg",
  LogoLeft: "/icons/Bulk/logoLeft.svg",
  LogoRight: "/icons/Bulk/logoRight.svg",
  // Stroke
  Add_funds_stroke: "/icons/Stroke/Add funds.svg",
  Affiliates_stroke: "/icons/Stroke/Affiliates.svg",
  Api_stroke: "/icons/Stroke/Api.svg",
  Arrow_crypto: "/icons/Stroke/Arrow Crypto.svg",
  Arrow_tooltip_left: "/icons/Stroke/Arrow Tooltip Left.svg",
  Arrow_tooltip_right: "/icons/Stroke/Arrow Tooltip Right.svg",
  Child_panel: "/icons/Stroke/Child panel.svg",
  Close: "/icons/Stroke/Close.svg",
  Dashboard: "/icons/Stroke/Dashboard.svg",
  Discord: "/icons/Stroke/Discord.svg",
  Done: "/icons/Stroke/Done.svg",
  DropDown_arrow_fill: "/icons/Stroke/DropDown Arrow Fill.svg",
  DropDown_arrow_stroke: "/icons/Stroke/DropDown Arrow Stroke.svg",
  Everything: "/icons/Stroke/Everything.svg",
  Facebook: "/icons/Stroke/Facebook.svg",
  Favorites_stroke: "/icons/Stroke/Favorites.svg",
  Favorites_fill: "/icons/Stroke/Favorites.svg",
  Google: "/icons/Stroke/Google.svg",
  History: "/icons/Stroke/History.svg",
  Info: "/icons/Stroke/Info.svg",
  Instagram: "/icons/Stroke/Instagram.svg",
  Linkedin_stroke: "/icons/Stroke/Linkedin.svg",
  Live_DW: "/icons/Stroke/Live DW.svg",
  Live_followers_counter: "/icons/Stroke/Live followers counter.svg",
  Okay: "/icons/Stroke/Okay.svg",
  Other: "/icons/Stroke/Other.svg",
  Photo_dw: "/icons/Stroke/Photo dw.svg",
  Plus: "/icons/Stroke/Plus.svg",
  Plus_stroke: "/icons/Stroke/Plus stroke.svg",
  Profile_tools: "/icons/Stroke/Profile tools.svg",
  Profile: "/icons/Stroke/Profile.svg",
  Question: "/icons/Stroke/Question.svg",
  Reels_DW: "/icons/Stroke/Reels DW.svg",
  Reorder: "/icons/Stroke/Reorder.svg",
  Search: "/icons/Stroke/Search.svg",
  Show: "/icons/Stroke/Show.svg",
  Snapchat: "/icons/Stroke/Snapchat.svg",
  Spotify: "/icons/Stroke/Spotify.svg",
  Stories: "/icons/Stroke/Stories.svg",
  Telegram: "/icons/Stroke/Telegram.svg",
  Tiktok: "/icons/Stroke/Tiktok.svg",
  Twitch: "/icons/Stroke/Twitch.svg",
  Twitter: "/icons/Stroke/Twitter.svg",
  Updates_stroke: "/icons/Stroke/Updates.svg",
  Video_DW: "/icons/Stroke/Video DW.svg",
  Warning: "/icons/Stroke/Warning.svg",
  Web_site: "/icons/Stroke/Web site.svg",
  Youtube: "/icons/Stroke/Youtube.svg",
  Eye: "/icons/Stroke/Eye.svg",
  Mask: "/icons/Stroke/MaskHappy.svg",
  Heart: "/icons/Stroke/Heart.svg",
  Heart_stroke: "/icons/Stroke/Heart_2.svg",
  Subtract: "/icons/Stroke/Subtract.svg",
  Arrow_right: "/icons/Stroke/Arrow right.svg",
  Arrow_left: "/icons/Stroke/Arrow left.svg",
  Burger: "/icons/Stroke/Burger.svg",
  Chat: "/icons/Stroke/Chat.svg",
  Group: "/icons/Stroke/Group.svg",
  Thunder: "/icons/Stroke/Thunder.svg",
  Unlock: "/icons/Stroke/Unlock.svg",
  Arrow_stroke_left: "/icons/Stroke/Arrow_stroke_left.svg",
  Money: "/icons/Stroke/Money.svg",
  Coins: "/icons/Stroke/Coins.svg",
  Purchase: "/icons/Stroke/Purchase.svg",
  Wallet: "/icons/Stroke/Wallet.svg",
  SoundOff: "/icons/Stroke/Sound off.svg",
  // Color
  Bitcoin: "/icons/Color/Bitcoin.svg",
  Crypto: "/icons/Color/Crypto.svg",
  Discord_color: "/icons/Color/Discord.svg",
  Facebook_color: "/icons/Color/Facebook.svg",
  Google_color: "/icons/Color/Google.svg",
  Instagram_color: "/icons/Color/Instagram.svg",
  Linkedin: "/icons/Color/Linkedin.svg",
  Medium: "/icons/Color/Medium.svg",
  Payeer: "/icons/Color/Payeer.svg",
  Payop: "/icons/Color/Payop.svg",
  Perfect_money: "/icons/Color/Perfect money.svg",
  Quora: "/icons/Color/Quora.svg",
  Reddit: "/icons/Color/Reddit.svg",
  Snapchat_color: "/icons/Color/Snapchat.svg",
  Spotify_color: "/icons/Color/Spotify.svg",
  Telegram_color: "/icons/Color/Telegram.svg",
  Tiktok_color: "/icons/Color/Tiktok.svg",
  Twitch_color: "/icons/Color/Twitch.svg",
  Twitter_color: "/icons/Color/Twitter.svg",
  Youtube_color: "/icons/Color/Youtube.svg",
  Trustpilot: "/icons/Color/Trustpilot.svg",
  Step_arrow: "/icons/Color/Step.svg",
  Line: "/icons/Color/Line.svg",
  Skype: "/icons/Color/Skype.svg",
  Pinterest: "/icons/Color/Pinterest.svg",
  Whatsapp: "/icons/Color/Whatsapp.svg",
  Gmail: "/icons/Color/Gmail.svg",
  Odnoklassniki: "/icons/Color/Odnoklassniki.svg",
  VK: "/icons/Color/VK.svg",

  Heart_2: "/icons/Best/Heart.svg",
  Comments: "/icons/Best/Comments.svg",
  Send: "/icons/Best/Send.svg",
  User: "/icons/Best/User.svg",

  Logo: "/logo.svg",
  Logo_2: "/logo 2.svg",
  Arc: "/icons/Color/arc.svg",
};

export const RanksIcons = {
  Bronze: "/icons/Ranks/Bronze.png",
  Diamond: "/icons/Ranks/Diamond.png",
  Gold: "/icons/Ranks/Gold.png",
  New: "/icons/Ranks/New.png",
  Platinum: "/icons/Ranks/Platinum.png",
  Silver: "/icons/Ranks/Silver.png",
  VIP3: "/icons/Ranks/VIP III.png",
  VIP: "/icons/Ranks/VIP.png",
};

export const FlagsIcons = {
  Australia: "/icons/Flags/Australia.svg",
  United_States: "/icons/Flags/United States.svg",
  Ukraine: "/icons/Flags/Ukraine.svg",
  Sweden: "/icons/Flags/Sweden.svg",
  United_Kingdom: "/icons/Flags/United Kingdom.svg",
  Canada: "/icons/Flags/Canada.svg",
};

export const GradientIcons = {
  News: "/icons/Gradient/News.png",
  Other: "/icons/Gradient/Other.png",
  Question: "/icons/Gradient/Question.png",
  Services: "/icons/Gradient/Services.png",
  Social: "/icons/Gradient/Social Media.png",
};

export const PaymentsIcons = {
  Payment1: "/icons/Payments/Payment Icons-4.svg",
  Payment2: "/icons/Payments/Payment Icons-3.svg",
  Payment3: "/icons/Payments/Payment Icons-2.svg",
  Payment4: "/icons/Payments/Payment Icons-1.svg",
  Payment5: "/icons/Payments/Payment Icons.svg",
};

export const CryptoIcons = {
  Crypto1: "/icons/Payments/Cryptocurrency.png",
  Crypto2: "/icons/Payments/Cryptocurrency-1.png",
  Crypto3: "/icons/Payments/Cryptocurrency-2.png",
  Crypto4: "/icons/Payments/Cryptocurrency-3.png",
  Crypto5: "/icons/Payments/Cryptocurrency-4.png",
  Crypto6: "/icons/Payments/Cryptocurrency-5.png",
};

export const ColorSvgVariants = {
  unset: "unset",
  inherit: "inherit",
  white: "white",
  light_blue: "light-blue",
  gray_text: "gray-text",
  gray: "gray",
  footer_text: "footer-text",
  elements: "elements",
  blocks: "blocks",
  menu: "menu",
  background: "background",
  black: "black",
  blue_light: "blue-light",
  blue: "blue",
  blue_dark: "blue-dark",
  yellow_light: "yellow-light",
  yellow: "yellow",
  yellow_dark: "yellow-dark",
  status_red: "status-red",
  status_blue: "status-blue",
  status_violet: "status-violet",
  status_orange: "status-orange",
  status_yellow: "status-yellow",
  status_green: "status-green",
};

export const ButtonVariants = {
  default: "default",
  crypto: "crypto",
  blue: "blue",
  yellow: "yellow",
  purchase: "purchase",
  side: "side",
};

export const ButtonSizeVariants = {
  extra_large: "xl",
  large: "lg",
  medium: "md",
  small: "sm",
};

export const AvatarVariants = {
  lg: "large",
  md: "medium",
  sm: "small",
};

export const NumberVariants = {
  lg: "large",
  md: "medium",
  sm: "small",
};

export const DropDownVariants = {
  profile: "profile",
  accordion: "accordion",
  select: "select",
};

export const SelectOptionVariants = {
  Detail: "detail",
  WithoutDeteil: "nodeteil",
  Default: "default",
  Format: "format",
};

export const TableVariants = {
  Ranks: "ranks",
  Redeem: "redeem",
  Subscriptions: "subscriptions",
  Orders: "orders",
  Service: "service",
  Service_detail: "serviceDetail",
  Payment: "payment",
  Completed: "completed",
  Affiliates: "affiliates",
};

export const TabsVariants = {
  Default: "default",
  Outline: "outline",
};
