export const OrdersSort = [
  "All",
  "Awaiting",
  "Pending",
  "In progress",
  "Completed",
  "Partial",
  "Canceled",
  "Processing",
  "Fail",
  "Error",
];

export const OrdersColumns = {
  checked: false,
  id: "ID",
  user: "User",
  charge: "Charge",
  link: "Link",
  startCount: "Start count",
  quantity: "Quantity",
  service: "Service",
  status: "Status",
  remains: "Remains",
  created: "Created",
  mode: "Mode",
};

export const OrdersInfo = [
  {
    checked: false,
    id: "1",
    user: "saidev",
    charge: 0.05,
    link: "https://www.naizop.com/profile",
    startCount: 1,
    quantity: 100,
    service: "Facebook likes",
    status: "Completed",
    remains: 0,
    created: "2022-04-11 08:10:39",
    mode: "Auto",
  },
  {
    checked: false,
    id: "2",
    user: "saidev",
    charge: 0.15,
    link: "https://www.naizop.com/profile",
    startCount: 405,
    quantity: 1000,
    service: "Facebook likes",
    status: "Completed",
    remains: 0,
    created: "2022-04-11 08:10:39",
    mode: "Auto",
  },
  {
    checked: false,
    id: "3",
    user: "saidev",
    charge: 0.025,
    link: "https://www.naizop.com/profile",
    startCount: 50,
    quantity: 1000,
    service: "Facebook likes",
    status: "Completed",
    remains: 0,
    created: "2022-04-11 08:10:39",
    mode: "Auto",
  },
  {
    checked: false,
    id: "4",
    user: "saidev",
    charge: 0.05,
    link: "https://www.naizop.com/profile",
    startCount: 405,
    quantity: 1000,
    service: "Facebook likes",
    status: "Completed",
    remains: 0,
    created: "2022-04-11 08:10:39",
    mode: "Auto",
  },
  {
    checked: false,
    id: "5",
    user: "saidev",
    charge: 0.05,
    link: "https://www.naizop.com/profile",
    startCount: 40,
    quantity: 400,
    service: "Facebook likes",
    status: "Completed",
    remains: 0,
    created: "2022-04-11 08:10:39",
    mode: "Manual",
  },
  {
    checked: false,
    id: "6",
    user: "saidev",
    charge: 0.05,
    link: "https://www.naizop.com/profile",
    startCount: 405,
    quantity: 1000,
    service: "Facebook likes",
    status: "Canceled",
    remains: 0,
    created: "2022-04-11 08:10:39",
    mode: "Auto",
  },
];
